{
    'name': 'Flamant KPI',
    'version': '18.0.7.1.0',
    'category': 'Sales/Sales',
    'summary': 'Consolidated POS + Sales KPI dashboard with channel / country / shop drilldown and margin reporting',
    'description': """Flamant KPI - Consolidated sales + margin reporting per channel/country/shop.""",
    'author': 'Digisolid',
    'website': 'https://digisolid.be',
    'depends': [
        'sales_team',
        'point_of_sale',
        'sale_management',
        'account_budget',
        'account_reports',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/menu_groups.xml',
        'views/crm_team_views.xml',
        'views/flamant_daily_sales_views.xml',
        'views/flamant_quotation_views.xml',
        'views/flamant_shop_budget_views.xml',
        'views/flamant_monthly_budget_views.xml',
        'views/flamant_bu_budget_views.xml',
        'views/menus.xml',
        'data/flamant_margin_report.xml',
        'data/flamant_business_unit_report.xml',
        'data/flamant_business_unit_report_grouped.xml',
    ],
    'assets': {},
    'post_init_hook': 'post_init_hook',
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
